-- Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
-- 
-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
-- 
-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
-- 
-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj|
-- is minimised; what is the value of D?

import Data.Set (fromList,member)

main = do print $ problem44'

p n = n*(3*n-1) `div` 2

limit = 5000 -- I don't know where the 5000 comes from, but it's used in my F# solutions.

ps = map p [1..limit]

-- This is my guess. I'm not going to run it, because I don't want it to run forever! LOL.
problem44 = minimum [k-j|n<-[1..limit], m<-[1..limit], n<m, let k=(p n), let j=(p m), k+j `elem` ps, k-j `elem` ps]

-- From greater minds than mine:
problem44' = head solutions
  where solutions = [a-b | a<-penta,
                           b<-takeWhile (<a) penta,
                           isPenta (a-b),
                           isPenta (a+b)]
        isPenta = (`member` fromList penta)
        penta = [(n * (3*n-1)) `div` 2 | n<-[1..5000]] -- There's that 5000 again! Where does that come from?
-- 5482660.
