-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
-- Triangle   Tn=n(n+1)/2   1, 3,  6, 10, 15, ...
-- Pentagonal Pn=n(3n-1)/2  1, 5, 12, 22, 35, ...
-- Hexagonal  Hn=n(2n-1)    1, 6, 15, 28, 45, ...
-- 
-- It can be verified that T285 = P165 = H143 = 40755.
-- 
-- Find the next triangle number that is also pentagonal and hexagonal.

t n = n*(n+1) `div` 2
p n = n*(3*n-1) `div` 2
h n = n*(2*n-1)

main = do print $ problem45'

-- We can ignore triangular numbers because all triangular numbers based on odd ns are hexagonal numbers.
-- That's pointed out at http://www.mathblog.dk/project-euler-45-next-triangle-pentagonal-hexagonal-number/.

problem45 = head $ [y|y<-[166..], z<-[145,147..], (p y) == (h z)]
-- Started at 13:03.
-- Killed after 14 minutes. :(

-- From greater minds than mine:
isPent n = (af==0) && ai `mod` 6 == 5
  where (ai,af) = properFraction . sqrt $ 1 + 24 * (fromInteger n)

problem45' = head [x|x<-scanl (+) 1 [5,9..], x>40755, isPent x]
-- 1533776805, instantaneously!
